### ISSUE TITLE
A couple of warnings when tapping the repo

### ISSUE THREAD

**Issue by cig0** [Git-Jiro/homebrew-jiro#54]
```
==> Tapping git-jiro/jiro
Cloning into '/usr/local/Homebrew/Library/Taps/git-jiro/homebrew-jiro'...
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/git-jiro/homebrew-jiro/gridcoin.rb:59:in `block in <class:Gridcoin>'
Please report this to the git-jiro/jiro tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/git-jiro/homebrew-jiro/gridcoin.rb:106:in `block in <class:Gridcoin>'
Please report this to the git-jiro/jiro tap!

Tapped 1 formula (31 files, 31.5KB)
```

**Comment by Git-Jiro** [comment]
Thank you for reporting this.
